# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Benjamin Dungeon
email: bend@hcasaints.com
description: > # this means to ignore newlines until "baseurl:"
  Hi, I am Benjamin Dungeon. This is my personal website. 
  It's a place where I can just post about whatever I feel like at the moment. 
  I hope you enjoy!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  BenjaminDungeon

# Build settings
markdown: kramdown
